Using Product model to define query
Appears to solve the issue all along, however is fails at the last line of data, as the last prodcut isn't insert
2019-06-04 17:08:22,950 INFO sqlalchemy.engine.base.Engine COMMIT
Traceback (most recent call last):
  File "/media/odin/RAGNAROCK_BACKUP/OFFood/setup.py", line 103, in <module>
    sub = products[n+1]
IndexError: list index out of range
16 | 0815126002179 | Sirop D'érable 250g Pur 100% Origine Canada - Noko   |        3 |         15 |           1 |
| 17 | 3088545004001 | Miel de fleurs - Lune de Miel - 500 g                |        3 |       NULL |           0
The honey product doesn't have its substitute in database...

So I solve inserting the 18th prodcut isse, I solve it all.
I need to solve :
2019-06-04 16:56:25,386 INFO sqlalchemy.engine.base.Engine COMMIT
# Traceback (most recent call last):
#   File "/media/odin/RAGNAROCK_BACKUP/OFFood/setup.py", line 80, in <module>
#     for index, (ean, name, category, substitute, substituted) in enumerate(prods):
# ValueError: too many values to unpack (expected 5)